APPEARANCE_MODE = "System"
COLOR_THEME = "blue"
APP_VERSION = "v0.5.4"
APP_WIDTH = 800
APP_HEIGHT = 450
APP_GEOMETRY = "{}x{}+{}+{}"
CANCELLED = "Cancelled!"
DOWNLOAD_CANCELLED = "Download Cancelled!"
SUCCESS = "Success!"
DOWNLOAD_SUCCESS = "Successfully downloaded the video!\ndownload path:{}\ndownload time: {}"
ERROR = "Error!"
INVALID_URL = "Invalid URL!\nPlease enter a valid Link!"
INVALID_VIDEO_ID = "The given video id is invalid."
EMPTY_URL_INPUT = "Please enter a Youtube video link to download"
FILE_EXISTS_TITLE = "File already exists"
FILE_EXISTS_MESSAGE = "A file with the same title already exists.\nDo you want to continue download? (existing file will be deleted)"
DOWNLOAD_TYPES = ["video", "audio", "video only"]
VIDEO_MIME_TYPES = ["mp4"]
ICON_CANCEL = "cancel"
ICON_WARNING = "warning"
