APP_VERSION = "v0.2.2"
APP_WIDTH = 500
APP_HEIGHT = 250
APP_GEOMETRY = "{}x{}+{}+{}"
CANCELLED = "Cancelled!"
DOWNLOAD_CANCELLED = "Download Cancelled!"
SUCCESS = "Success!"
DOWNLOAD_SUCCESS = "Successfully downloaded the video!\ndownload path:{}\ndownload time: {}"
ERROR = "Error!"
INVALID_URL = "Invalid URL!\nPlease enter a valid Link!"
INVALID_VIDEO_ID = "The given video id is invalid."
EMPTY_URL_INPUT = "Please enter a Youtube video link to download"
